[package]
name = "miss_me"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.38", features = ["derive"] }
crossterm = "0.29.0"
ratatui = "0.29.0"
tokio = { version = "1.45.0", features = ["full"] }
